name: ✨ Enhancement
description: Améliorer une fonctionnalité existante
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Amélioration souhaitée
      description: Décrivez simplement l'amélioration souhaitée
      placeholder: |
        Afficher le détail des calculs de combat (dés, bonus, etc.)
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Pourquoi c'est utile (optionnel)
      description: Pourquoi cette amélioration serait importante ?
      placeholder: |
        Pour que les joueurs comprennent mieux les mécaniques.
    validations:
      required: false
