name: 🚀 Feature Request
description: Proposer une nouvelle fonctionnalité pour Adventure Tome
title: "[Feature]: "
labels: ["type: feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Décrivez la fonctionnalité souhaitée simplement
      placeholder: |
        Je veux pouvoir supprimer les items personnalisés que j'ai créés.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contexte
      description: Pourquoi est-ce utile ? (optionnel)
      placeholder: |
        Actuellement, une fois créé, on ne peut plus supprimer un item personnalisé.
    validations:
      required: false
