name: ♻️ Refactor
description: Proposer une refactorisation du code existant
title: "[Refactor]: "
labels: ["type: refactor"]
body:
  - type: textarea
    id: description
    attributes:
      label: Refactorisation souhaitée
      description: Décrivez simplement ce que vous voulez refactoriser
      placeholder: |
        Simplifier le système d'inventaire pour éviter la duplication des données.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Pourquoi c'est utile (optionnel)
      description: Quel problème technique cela résout-il ?
      placeholder: |
        Ça réduira la complexité et facilitera la maintenance.
    validations:
      required: false
